spring:
  application.name: payment-api
  datasource:
    url: jdbc:h2:mem:payment
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true