name: CI & CD
on: [push, pull_request, workflow_dispatch]

env:
  JAR_NAME: payment-api-local-SNAPSHOT.jar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: test and build
        run: mvn clean verify -U
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: payment-api-artifact
          path: |
            target/${{ env.JAR_NAME }}
            Dockerfile
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: payment-api-artifact
      - name: Display artifact
        run: pwd && ls -l
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment-api:latest
          build-args: module=${{ env.JAR_NAME }}